export const ROOM_TYPES = [
  "kitchen", "bathroom", "bedroom", "living room", "dining room",
  "laundry room", "basement", "home office", "entryway", "backyard",
  "front porch", "garage", "attic bedroom", "guest bathroom",
  "master bedroom", "kids bedroom", "nursery", "walk-in closet",
  "pantry", "mudroom",
];

export const ROOM_CONDITIONS = [
  "outdated and ugly", "old and worn out", "builder-grade and boring",
  "stuck in the 90s", "needs a complete makeover", "cheap-looking and dated",
  "dark and cramped-feeling", "bland and lifeless", "embarrassingly outdated",
  "desperately needs updating", "plain and uninspired", "dull and forgettable",
];

export const ROOM_DETAILS = [
  "oak cabinets, beige countertops, and black appliances",
  "old tile, yellow lighting, and outdated fixtures",
  "popcorn ceiling, carpet, and brass hardware",
  "laminate everything and fluorescent lights",
  "wood paneling and shag carpet",
  "pink tile, floral wallpaper, and gold fixtures",
  "white wire shelving and bare walls",
  "mismatched furniture and bad paint colors",
  "old linoleum, water stains, and peeling paint",
  "brown carpet, ceiling fan, and beige walls",
  "small windows, dark cabinets, and no counter space",
  "old appliances, chipped counters, and stained grout",
];

export const REMODEL_STYLES = [
  "warm modern with walnut wood and soft lighting",
  "organic modern with natural materials and curved furniture",
  "warm minimalist with light wood, linen, and soft neutrals",
  "earthy and grounded with terracotta, stone, and raw wood",
  "warm wood tones with rattan accents and soft ambient lighting",
  "natural and textured with woven materials and muted earth tones",
  "warm neutral with cream, beige, and layered textures",
  "honey oak and warm brass with soft white walls",
  "warm Japandi with light wood, paper lanterns, and simple forms",
  "desert modern with sand tones, curves, and natural stone",
  "bright white farmhouse with shiplap and pendant lights",
  "all-white and airy with subtle texture and greenery",
  "clean white with marble countertops and brass hardware",
  "bright Scandinavian with white walls, light wood, and soft rugs",
  "crisp white with black accents and modern fixtures",
  "light and fresh with soft pastels and natural light",
  "white oak and white quartz with minimal hardware",
  "bright coastal with white, light blue, and woven baskets",
  "white with warm wood floating shelves and plants",
  "fresh and modern with white subway tile and open shelving",
  "dark and moody with matte black and marble",
  "deep charcoal with brass accents and warm lighting",
  "dark green walls with gold hardware and rich wood",
  "moody navy blue with white trim and warm metals",
  "dramatic black with walnut wood and statement lighting",
  "dark forest green with leather and warm wood",
  "charcoal and marble with subtle gold details",
  "inky blue with cream accents and textured fabrics",
  "dark chocolate brown with warm amber lighting",
  "rich burgundy accent wall with warm neutrals",
  "industrial with exposed brick, concrete, and metal",
  "urban loft with concrete floors, black steel, and warm wood",
  "raw industrial with pipe shelving and Edison bulbs",
  "modern industrial with polished concrete and matte black",
  "factory-style with metal accents, brick, and warm leather",
  "rustic with reclaimed wood, stone, and warm earth tones",
  "modern farmhouse with shaker cabinets and apron sink",
  "cozy cottage with soft fabrics, warm wood, and open shelving",
  "French country with soft colors, vintage details, and charm",
  "English countryside with floral patterns and antique wood",
  "cabin-style with knotty pine, plaid, and warm flannel tones",
  "Tuscan with warm terracotta, wrought iron, and stone arches",
  "vintage farmhouse with distressed wood and enamel fixtures",
  "Scandinavian minimal with light wood and clean lines",
  "Nordic cozy with sheepskin, warm knits, and candlelight",
  "Swedish style with pale blue, white wood, and linen curtains",
  "Danish modern with teak furniture and warm pops of color",
  "mid-century modern with warm tones and retro touches",
  "1970s retro with warm wood, burnt orange, and textured glass",
  "Palm Springs mid-century with terrazzo, pastels, and clean lines",
  "retro diner style with checkerboard floors and chrome accents",
  "vintage 1960s with teak, mustard yellow, and geometric patterns",
  "Mediterranean with terracotta, arches, and warm colors",
  "Greek island with white stucco, blue accents, and natural stone",
  "tropical with lush green, rattan, and warm wood",
  "coastal with sandy tones, driftwood, and sea glass accents",
  "Moroccan with zellige tile, arches, and warm lanterns",
  "Spanish colonial with terra cotta tile, dark wood, and iron",
  "Japanese minimalist with natural wood and sliding panels",
  "Zen-inspired with bamboo, stone, and soft indirect lighting",
  "Korean modern with soft curves, warm wood, and clean surfaces",
  "Balinese with teak wood, stone accents, and tropical plants",
  "contemporary with clean lines, neutral tones, and bold art",
  "sleek modern with flat panel cabinets and hidden storage",
  "ultra-modern with integrated lighting and seamless surfaces",
  "modern monochrome with black, white, and gray",
  "contemporary glam with mirrored surfaces and crystal accents",
  "futuristic with smooth surfaces, LED accents, and cool tones",
  "luxurious and glam with gold accents and rich materials",
  "Hollywood Regency with velvet, mirrors, and lacquer",
  "Art Deco with geometric patterns, gold, and dark green marble",
  "boutique hotel style with layered textures and statement lighting",
  "quiet luxury with cashmere, stone, and warm metals",
  "high-end penthouse with dark wood, leather, and ambient lighting",
  "bold and colorful with statement tiles and fun patterns",
  "maximalist with rich patterns, textures, and collected objects",
  "eclectic bohemian with layered rugs, plants, and warm light",
  "color-drenched with a single bold color in varying shades",
  "playful and vibrant with unexpected color combinations",
  "jewel-toned with emerald, sapphire, and amethyst accents",
  "vintage eclectic with mismatched furniture and antique finds",
  "modern heritage with classic moldings and updated finishes",
  "Parisian apartment with herringbone floors and ornate molding",
  "Brooklyn brownstone with warm dark tones and vintage charm",
  "Australian coastal with pale timber, concrete, and soft blue",
  "New England classic with wainscoting, navy, and brass",
  "modern Mexican with terracotta, hand-painted tile, and bold color",
  "Brazilian modernist with warm wood, bold curves, and lush plants",
  "Pacific Northwest with cedar, moss green, and natural stone",
  "converted warehouse with exposed beams, glass, and steel",
  "library-style with dark wood, built-in bookshelves, and leather",
  "spa-style with soft stone, warm wood, and ambient lighting",
  "greenhouse-style with glass, white steel, and tons of plants",
  "black and white with bold graphic patterns and clean lines",
  "soft romantic with blush tones, gold, and flowing fabrics",
  "architect's studio with concrete, plywood, and functional design",
  "lakehouse with knotty alder, stone fireplace, and cozy textures",
  "modern Tudor with dark beams, plaster walls, and updated fixtures",
  "Havana-inspired with colorful tile, tropical wood, and arched windows",
  "chalet-style with dark wood, stone, and plush textiles",
];

export const A2_TITLES = [
  "what would you pick for my remodel? \u{1f605}",
  "help me choose a design for this room \u{1f64f}",
  "which style would you pick?? I can't decide \u{1f629}",
  "pls help us choose a remodel style",
  "we can't agree on a style\u2026 which would you pick?",
  "what design would you go with for this room??",
  "my husband and I can't decide\u2026 help us pick \u{1f62d}",
  "I desperately need this room remodeled \u{1f62b} help me choose",
  "which option would you choose?? swipe to see \u2192",
  "pls help me pick a style for this remodel",
  "what style should I choose?? \u{1f914}",
  "it's so hard to choose\u2026 what would you pick??",
  "we need help choosing a design pls help \u{1f64f}",
  "which remodel would you go with??",
  "idk what to do with this room\u2026 help me choose",
  "what design would you pick for this space??",
  "I can't pick between these\u2026 which one wins?",
  "my bf and I can't agree on a style \u{1f629} help",
  "what would you choose for this makeover?? swipe \u2192",
  "help!! which design should I go with??",
  "we bought this house and this room needs help \u{1f605}",
  "pls help me choose a design \u{1f97a}",
  "which style is your favorite?? comment below",
  "I need to remodel this room but can't pick a style",
  "what would you do with this room?? I need ideas",
  "this room needs a serious glow up\u2026 which style?? \u{1f629}",
  "vote for your favorite remodel \u{1f5f3}\ufe0f",
  "which option are you going with?? swipe \u2192",
  "we're remodeling soon and I can't decide \u{1f62d}",
  "help me pick a style I'm so indecisive \u{1f62b}",
  "which design would you actually live with??",
  "this room is giving 1995\u2026 help me fix it \u{1f605}",
  "swipe to see the options \u2192 which is your fave??",
  "comment your pick!! I'll go with the most popular one \u{1f447}",
  "my mom says option 1 but I say option 3\u2026 who wins??",
  "we need to remodel this ASAP which style?? \u{1f64f}",
  "I've been staring at paint samples for weeks \u{1f629} just pick for me",
  "which makeover would you choose??",
  "help us settle this debate \u{1f624} which design is better??",
  "what style screams YOU?? comment below \u{1f447}",
  "this room has been like this for 10 years\u2026 time for a change \u{1f62d}",
  "which one would make you stop and say wow?? \u{1f60d}",
  "I can't choose\u2026 every option is so different \u{1f605}",
  "pls help I've been going back and forth for weeks",
  "would you go bold or keep it neutral?? \u{1f914}",
  "which remodel is worth the money??",
  "swipe and pick your favorite design \u{1f440}",
  "I need your honest opinion\u2026 which style?? \u{1f629}",
  "help!! too many good options I can't pick \u{1f62d}",
  "what's your dream remodel style?? show me in the comments",
];

export const A2_CAPTIONS = [
  "this room is stuck in the 90s and I need it remodeled asap \u{1f629} which style would you pick??",
  "swipe to see 5 completely different remodel options \u2192 which one wins??",
  "I can't pick a style for this remodel\u2026 help me decide \u{1f62d}",
  "we just bought this house and this room needs serious help \u{1f605}",
  "the before is rough but the options are \u{1f525} which would you go with??",
  "comment your number \u{1f447} I'm going with whatever gets the most votes",
  "my husband wants option 2 but I want option 4\u2026 who's right?? \u{1f624}",
  "this is what AI thinks my remodel should look like \u{1f92f}",
  "which remodel style matches your vibe?? drop your pick below \u{1f447}",
  "save this if you're planning a remodel \u{1f4cc} so many good options",
  "POV: you finally remodel that room you've been ignoring for years \u{1f602}",
  "option 3 is calling my name \u{1f60d} but what do you think??",
  "I showed my mom and she picked option 1\u2026 do we trust her taste?? \u{1f605}",
  "every option hits different \u{1f525} which one would you actually live in??",
  "this room went from \u{1f62c} to \u{1f60d} real quick",
  "tag someone who desperately needs a room remodel \u{1f602}",
  "I literally cannot choose\u2026 swipe and help me pick \u{1f64f}",
  "the glow up is insane \u{1f92f} which style would you go with??",
  "if budget wasn't a thing which one are you picking?? \u{1f4b0}",
  "your remodel inspo for the day \u2728 save for later",
  "we're remodeling this room next month and I need your vote \u{1f5f3}\ufe0f",
  "be honest\u2026 could you live with option 5?? \u{1f602}",
  "my budget says option 1 but my heart says option 4 \u{1f629}",
  "this room really said glow up \u2728",
  "which design are you screenshotting?? \u{1f4f1}\u{1f447}",
  "we've been arguing about this for weeks\u2026 settle it for us \u{1f624}",
  "this room has looked like this since 2003 and I'm done \u{1f62d}",
  "swipe to see the options and tell me which one to go with \u{1f64f}",
  "I'm picking whichever one gets the most comments \u{1f447}",
  "ngl I changed my mind 3 times while making this \u{1f605}",
  "which style would increase the home value the most?? \u{1f914}",
  "my contractor is waiting for my decision and I still can't choose \u{1f629}",
  "the before photo is embarrassing but the options are amazing \u{1f525}",
  "save this for when you're ready to remodel \u{1f4cc}",
  "I never thought this room could look this good \u{1f92f}",
  "which one matches your aesthetic?? comment below \u{1f447}",
  "this is the motivation I needed to finally start remodeling \u2728",
  "tell me your pick without overthinking it\u2026 go \u{1f447}",
  "option 1 is safe but option 4 is bold\u2026 which do you choose??",
  "drop a \u{1f525} for your favorite and a \u{1f480} for your least favorite",
  "POV: you realize your room could actually look like this \u{1f60d}",
  "I'm genuinely going to remodel based on your comments \u{1f5f3}\ufe0f",
  "this room went from tragic to magic \u2728 which option??",
  "my realtor would cry if they saw the before \u{1f602}",
  "swipe to see 5 styles you never knew you needed",
  "comment the number and I'll reveal which one I picked next week \u{1f440}",
  "the before makes me cringe every time \u{1f62c} but look at these options",
  "which design would make you never want to leave this room??",
  "your vote decides my remodel\u2026 no pressure \u{1f605}",
  "honestly all of these are an upgrade over what I have now \u{1f62d}",
];

export const HOME_STYLES = [
  "1990s builder-grade beige",
  "2010s gray-and-white modern",
  "1970s wood-paneled",
  "1980s brick-and-carpet",
  "new construction white farmhouse",
  "old Victorian with crown molding",
  "early 2000s tan and brown suburban",
  "converted old church or chapel",
  "British terraced house with plaster walls",
  "mid-century split-level",
  "old brownstone with ornate trim",
];

export const LIGHTINGS = [
  "warm yellow overhead", "natural window light", "dim hallway",
  "bright daylight flooding in", "single wall sconce lamp",
  "harsh ceiling spotlight", "soft overcast light from a nearby window",
  "mixed natural and warm artificial light",
];
