export const SPACE_TYPES = [
  "under-staircase triangular nook",
  "narrow hallway dead-end",
  "weird arched wall alcove",
  "empty recessed cutout above a door",
  "small half-landing on stairs",
  "odd corner where two walls meet at a weird angle",
  "unused closet with door removed",
  "random built-in shelf nook by a window",
  "gap between fridge and wall",
  "awkward L-shaped entryway corner",
  "random structural pillar in the middle of a room",
  "sunken floor pit in a living room",
  "awkward sloped ceiling attic corner",
  "tiny bathroom nook with exposed pipes",
  "random column in a bedroom",
  "curved wall alcove near a staircase",
  "small landing at the top of stairs with a railing",
  "recessed wall cutout next to a bathtub",
  "gap under a sloped roofline next to a bed",
  "arched doorway alcove in an old house",
  "narrow space between a staircase wall and living room",
  "weird triangular corner where a roof slope meets the wall",
  "small square cutout window nook in a stairwell",
  "random step-down between two rooms",
  "exposed pipe corner in a finished basement",
  "high wall ledge above a staircase with an arched window",
  "empty open space under an open staircase with metal railing",
  "tall narrow wall niche between two doorways",
  "dead corner behind a staircase banister",
  "random AC unit bump-out shelf above a door",
  "wide shallow alcove at the bottom of stairs",
  "open loft overhang looking down to a foyer",
  "unfinished crawlspace opening in a finished room",
  "angled wall cutout under a second-floor overhang",
  "empty coat closet area with just hooks and a shelf",
  "double-height foyer wall with nothing on it",
  "staircase landing with a large arched window",
  "odd triangular space where stairs turn a corner",
  "gap between washer/dryer and wall in a laundry room",
];

export const HOME_STYLES = [
  "1990s builder-grade beige",
  "2010s gray-and-white modern",
  "1970s wood-paneled",
  "1980s brick-and-carpet",
  "new construction white farmhouse",
  "old Victorian with crown molding",
  "early 2000s tan and brown suburban",
  "converted old church or chapel",
  "British terraced house with plaster walls",
  "mid-century split-level",
  "old brownstone with ornate trim",
];

export const FLOORINGS = [
  "beige carpet", "dark hardwood", "light oak laminate", "tile",
  "linoleum", "gray carpet", "worn brown carpet", "white tile",
  "dark stained wood stairs", "cream marble tile",
];

export const LIGHTINGS = [
  "warm yellow overhead", "natural window light", "dim hallway",
  "bright daylight flooding in", "single wall sconce lamp",
  "harsh ceiling spotlight", "soft overcast light from a nearby window",
  "mixed natural and warm artificial light",
];

export const VIBES = [
  "a cozy and inviting little nook", "something clean and aesthetic",
  "a practical but beautiful setup", "something warm and lived-in",
  "a clever storage solution that looks gorgeous", "something modern and minimal",
  "a small but luxurious upgrade", "something soft and calming",
  "a stylish use of the space", "something earthy and natural",
  "a Pinterest-worthy transformation", "something bright and airy",
  "something moody and intimate", "a functional space that also looks beautiful",
  "something rustic and charming", "a surprisingly elegant solution",
  "something with texture and warmth", "a creative use of every inch",
  "something with plants and natural materials", "a space that feels intentional and designed",
  "something Scandinavian and effortless", "something dark and dramatic but tasteful",
  "a dreamy transformation that feels expensive", "something with warm wood tones and soft light",
  "a peaceful spot you'd never want to leave", "something that makes the whole room feel upgraded",
  "a transformation that looks like it costs thousands but doesn't",
  "something with an accent wall that ties everything together",
  "a sophisticated little corner", "something that makes the space feel twice as big",
  "something coastal and breezy", "something with arches and curves",
  "a space that feels like a boutique hotel", "something with rich colors and warm materials",
  "a subtle but stunning upgrade", "something that would get saved on Pinterest a thousand times",
  "a transformation that makes people ask where you got everything",
  "something with mirrors that opens up the space", "something Japanese-inspired and serene",
  "something with hidden storage that looks seamless", "something Art Deco with gold accents",
  "a space that feels like a page from a magazine", "something with stone and natural finishes",
  "something that turns dead space into a feature", "a spot that makes the whole house feel more expensive",
  "something timeless that will never go out of style",
  "something with layered textures and neutral tones",
  "a tiny space that feels like its own little world",
  "something that balances form and function perfectly",
  "a transformation so clean it looks AI-generated",
  "a tiny fast food chain restaurant", "a cat playground", "a dog playground",
  "a tiny pool", "a Christmas-themed corner", "a mini bowling alley", "a little indoor garden",
  "something hilarious and unexpected",
  "something funny and strange that people don't normally put in homes",
  "something absurd that would go viral", "something weirdly genius",
  "something a kid would dream up", "something useful that actually solves a real problem",
  "something ridiculously bougie for such a small space",
  "something completely unhinged but oddly functional",
  "something so dumb it's genius", "something that would start an argument in the comments",
  "something that has no business being in a house",
  "something that would make your landlord cry",
  "something chaotic but it somehow works", "something impressively useless",
  "something that looks expensive but is completely pointless", "something unserious",
  "something that would confuse every guest who visits",
  "something that would make your realtor question everything",
  "something only a divorced dad would build",
  "something that screams 'I live alone and I don't care'",
  "something that would get roasted on Reddit",
  "something that would make an interior designer have a breakdown",
  "something a villain would have in their house",
  "something that only makes sense at 3am",
  "something that would make your mom call you",
  "something that looks way too fancy for a random corner",
  "something aggressively random",
  "something that would make people screenshot and send to their group chat",
  "something that belongs in a cartoon",
  "something your HOA would send a letter about",
  "something that would make a contractor walk out",
  "something that would divide the internet",
  "something that would make people say 'but why'",
  "something unhinged but aesthetically pleasing",
  "something that would make your neighbors concerned",
  "something that would get 10,000 comments saying 'I need this'",
  "something only a millionaire or a maniac would build",
  "something that would make people think you're going through something",
  "something that would make house hunters walk right out",
  "something that would make people pause and rewatch",
  "something that would make people save the video",
  "something that radiates chaotic good energy",
  "something that would make your ex regret leaving",
  "something that would go viral for all the wrong reasons",
  "something that makes the house feel like a theme park",
  "something that no one would expect but everyone would want",
  "something that would make people tag their friends",
  "something that would make people duet the video",
  "something that would make a minimalist lose their mind",
  "something that would make people argue about whether it's genius or stupid",
];

export const A1_TITLES = [
  "HELP!! what should I do with this space?? \u{1f629}",
  "help??? what do I do with this?? \u{1f62d}",
  "HELP! what would you do with this awkward space?",
  "what should I do with this space?? \u{1f914}",
  "pls help me figure out what to do here \u{1f605}",
  "I've been staring at this space for months\u2026 help",
  "this space has been empty since we moved in \u{1f629}",
  "what would you put here?? I'm so lost",
  "HELPPP I need ideas for this spot \u{1f62d}",
  "we can't figure out what to do with this space",
  "what should I do with this?? help \u{1f62b}",
  "I've tried everything and nothing works here",
  "this awkward space is driving me crazy",
  "what would you do with this dead space?? \u{1f440}",
  "someone please help me with this \u{1f64f}",
  "how do I make this space actually useful??",
  "this spot has been empty for 3 years\u2026 ideas??",
  "I need your help with this space \u{1f629}\u{1f629}",
  "what would you put here??",
  "help me figure out what to do here pls \u{1f97a}",
  "who has ideas for this space?? I'm stuck",
  "what do I do with this?? \u{1f62d}\u{1f62d}",
  "this space is so awkward I can't figure it out",
  "literally what goes here??",
  "someone tell me what to do with this spot \u{1f605}",
  "HELP what do I do with this empty space?? \u{1f629}",
  "we just moved in and I have no idea what to do here",
  "this space mocks me every single day \u{1f62d}",
  "what would YOU do with this space??",
  "pls give me ideas I'm begging \u{1f64f}\u{1f629}",
  "I walk past this every day and it drives me insane",
  "what should I put here?? nothing fits \u{1f62b}",
  "this has to be the weirdest space in any house",
  "help!! I don't know what to do with this \u{1f605}",
  "does anyone else have this problem?? what did you do??",
  "my house has SO many of these spaces \u{1f62d}",
  "what would you do if this was your house??",
  "I've given up trying to figure this out\u2026 help \u{1f629}",
  "someone pls tell me what goes here",
  "the previous owners left this completely empty \u{1f605}",
  "why does this space even exist?? \u{1f62d}",
  "I need ideas ASAP what would you do here??",
  "this space is begging to be something\u2026 but what?? \u{1f914}",
  "how would you use this space?? I'm clueless",
  "help me turn this into something amazing \u{1f64f}",
  "what should I do with this random space?? \u{1f629}",
  "every guest asks about this space and I have no answer \u{1f602}",
  "I've been avoiding this space for too long",
  "pls help what do I put here?? \u{1f62d}",
  "I cannot figure out what to do with this \u{1f62b}\u{1f62b}",
];

export const A1_CAPTIONS = [
  "this space has been empty since we moved in and I finally want to do something with it \u{1f629} drop your ideas below",
  "I have no idea what to put here\u2026 what would you do??",
  "swipe to see the redesign \u{1f440} which one is your fave?",
  "someone pls tell me what to do with this space \u{1f62d}",
  "been ignoring this space for too long\u2026 finally tried redesigning it \u2728",
  "this might be the most awkward space in any house ever \u{1f605} swipe to see ideas",
  "which transformation would you actually do?? comment your pick \u{1f447}",
  "I never know what to do with spaces like this \u{1f629}",
  "swipe \u2192 the last one is my favorite \u{1f60d}",
  "would you keep it empty or actually use this space?? \u{1f914}",
  "this space has been driving me crazy \u{1f624} what would you put here??",
  "trying to figure out what to do with every awkward space in my house \u{1f602}",
  "the AI went crazy on this one \u{1f92f} which design do you like best??",
  "save this for inspo if you have a space like this \u{1f4cc}",
  "I asked AI to redesign this space and I'm actually obsessed \u{1f60d}",
  "POV: you finally figure out what to do with that empty space \u{1f64c}",
  "tag someone who has this exact same problem \u{1f602}",
  "which one would you actually live with?? be honest \u{1f447}",
  "this space finally has a purpose \u2728 swipe to see options",
  "I can't decide which one I like more\u2026 help me pick \u{1f629}",
  "why do builders leave these random spaces everywhere \u{1f62d}",
  "swipe to see what AI did with this space \u{1f92f}",
  "I tried 5 different ideas for this space\u2026 which wins??",
  "this space went from useless to \u{1f60d}",
  "which one are you saving?? \u{1f4cc}\u{1f447}",
  "every house has that one space you don't know what to do with \u{1f605}",
  "comment what you'd put here\u2026 I need real ideas \u{1f447}",
  "swipe to see the glow up \u2728 this space finally looks good",
  "my house has like 5 of these and I'm losing my mind \u{1f62d}",
  "tell me which one to go with and I'll actually do it",
  "I've been scrolling for inspo for weeks and finally found something \u{1f92f}",
  "this is the space that haunts me every day \u{1f629} finally did something about it",
  "you guys always have the best ideas\u2026 what would you do?? \u{1f447}",
  "the transformation is actually insane \u{1f525} which option do you like??",
  "POV: that random space in your house finally gets some love \u2728",
  "idk about you but I'm obsessed with the last one \u{1f60d}",
  "save this if you're moving into a new house soon \u{1f4cc}",
  "which one is the most realistic?? I actually want to build this",
  "drop a \u{1f525} for your favorite option",
  "this space has been mocking me for years \u{1f624} not anymore",
  "be honest which one would you actually pick??",
  "my friends are split on this\u2026 settle the debate \u{1f447}",
  "I showed these to my family and everyone picked a different one \u{1f602}",
  "which design gives the best vibes?? I genuinely can't choose",
  "swipe to see what this space could be \u2728 the last one is wild",
  "no one asked but I redesigned this space 5 different ways \u{1f605}",
  "I think about this space more than I should \u{1f602} which one wins??",
  "comment your number and I'll tally the votes \u{1f5f3}\ufe0f",
  "this went from the worst spot in the house to the best \u{1f92f}",
  "would you actually do any of these?? or leave it empty \u{1f914}",
];
