// Cloudflare Worker entry: the OpenNext-generated Next.js handler plus a
// scheduled() handler for the Cron Triggers in wrangler.jsonc.
// See https://opennext.js.org/cloudflare/howtos/custom-worker
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { runCronJobs } from "./cloudflare/cron";

type Fetcher = { fetch(request: Request): Promise<Response> };
type Env = { WORKER_SELF_REFERENCE?: Fetcher; CRON_SECRET?: string } & Record<string, unknown>;
type Ctx = { waitUntil(promise: Promise<unknown>): void; passThroughOnException?(): void };
type ScheduledEvent = { cron: string; scheduledTime: number };

const worker = {
  fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> {
    return handler.fetch(request, env, ctx);
  },

  async scheduled(event: ScheduledEvent, env: Env, ctx: Ctx): Promise<void> {
    // Each job goes through the self service binding so it runs as its own
    // request with its own CPU and subrequest budget, like a Vercel invocation.
    const send = (request: Request) =>
      env.WORKER_SELF_REFERENCE
        ? env.WORKER_SELF_REFERENCE.fetch(request)
        : handler.fetch(request, env, ctx);
    const secret = typeof env.CRON_SECRET === "string" ? env.CRON_SECRET : undefined;
    if (!secret) console.error("CRON_SECRET is not set; cron routes will reject the call");

    const results = await runCronJobs(event.cron, send, secret);
    for (const r of results) {
      console.log(`cron ${event.cron} ${r.path} -> ${r.status}${r.ok ? "" : ` ${r.body}`}`);
    }
    const failed = results.filter((r) => !r.ok);
    if (failed.length) {
      throw new Error(`cron ${event.cron}: ${failed.map((r) => `${r.path} ${r.status}`).join(", ")}`);
    }
  },
};

export default worker;
